# Generated by Django 5.2 on 2026-03-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("verified", "Verified"),
                    ("setup_incomplete", "Setup Incomplete"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                ],
                db_index=True,
                default="unverified",
                help_text="User status",
                max_length=20,
            ),
        ),
    ]
